export const categories = [
  "Electronics",
  "Fashion",
  "Home & Kitchen",
  "Sports ",
  "Beauty",
  "Automotive",
];
export const mockData = [
  {
    id: 1,
    title: "T-Shirt",
    description:
      "Comfortable and stylish cotton t-shirt perfect for everyday wear",
    price: 29.99,
    discountPrice: 24.99,
    category: "Men",
    subCategory: "Clothing",
    brand: "FashionCo",
    rating: 4.5,
    reviews: 128,
    stock: 50,
    images:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLCu-ElEeR7aUgSHsli5Tx84rzNR1xvUalzvgo8_rnDIMV5H4wfqvwlftNZ4vOUUBlMts&usqp=CAU",
    colors: ["White", "Black", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    isFeatured: true,
    isNewArrival: true,
    tags: ["summer", "casual", "cotton"],
  },
  {
    id: 2,
    title: "Headphones",
    description:
      "High-quality wireless headphones with active noise cancellation",
    price: 199.99,
    discountPrice: 169.99,
    category: "Electronics",
    subCategory: "Audio",
    brand: "SoundMax",
    rating: 4.8,
    reviews: 256,
    stock: 30,
    images:
      "https://plus.unsplash.com/premium_photo-1678099940967-73fe30680949?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8aGVhZHBob25lc3xlbnwwfHwwfHx8MA%3D%3D&fm=jpg&q=60&w=3000",
    colors: ["Black", "Silver", "Rose Gold"],
    features: ["40h battery", "Touch controls", "Voice assistant"],
    isFeatured: true,
    isNewArrival: false,
    tags: ["technology", "music", "wireless"],
  },
  {
    id: 3,
    title: " Handbag",
    description: "Elegant leather handbag with gold-plated hardware",
    price: 299.99,
    discountPrice: 249.99,
    category: "Women",
    subCategory: "Accessories",
    brand: "LuxStyle",
    rating: 4.7,
    reviews: 89,
    stock: 15,
    images:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQcdL9sLA9mTjYgkPfi21ZcvYhxHccDOfvTSarZvTpPyB0d13J5jYb4OpZ2TJE-QFseAetTlPEN-h7Zqji2Pmj6rZd0ifQJJ6PWDsc8mhVl-_CyIf_v3bImfA",
    colors: ["Brown", "Black", "Tan"],
    dimensions: "14 x 10 x 5 inches",
    isFeatured: true,
    isNewArrival: true,
    tags: ["fashion", "luxury", "leather"],
  },
  {
    id: 4,
    title: " Watch",
    description: "Advanced fitness tracker with heart rate monitoring",
    price: 149.99,
    discountPrice: 129.99,
    category: "Electronics",
    subCategory: "Wearables",
    brand: "TechFit",
    rating: 4.6,
    reviews: 312,
    stock: 45,
    images: "https://images6.alphacoders.com/394/thumb-1920-394174.jpg",
    colors: ["Black", "Blue", "Pink"],
    features: ["Heart rate monitor", "Sleep tracking", "Water resistant"],
    isFeatured: false,
    isNewArrival: true,
    tags: ["fitness", "technology", "health"],
  },
  {
    id: 5,
    title: "Tablet",
    description:
      "Child-friendly tablet with educational apps and parental controls",
    price: 179.99,
    discountPrice: 159.99,
    category: "Kids",
    subCategory: "Electronics",
    brand: "KidsLearn",
    rating: 4.4,
    reviews: 156,
    stock: 25,
    images:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyK_6isgpKKd2X1X7f2fbyAm9ImiPkafCF8Q&s",
    colors: ["Blue", "Pink", "Green"],
    features: ["Parental controls", "Educational apps", "Durable case"],
    isFeatured: true,
    isNewArrival: false,
    tags: ["education", "technology", "kids"],
  },
];
